name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-14
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && 
       (contains(github.event.head_commit.message, 'feat:') ||
        contains(github.event.head_commit.message, 'feat(') ||
        contains(github.event.head_commit.message, 'fix:') ||
        contains(github.event.head_commit.message, 'fix(') ||
        contains(github.event.head_commit.message, 'perf:') ||
        contains(github.event.head_commit.message, 'perf(') ||
        contains(github.event.head_commit.message, 'revert:') ||
        contains(github.event.head_commit.message, 'revert(') ||
        contains(github.event.head_commit.message, 'refactor:') ||
        contains(github.event.head_commit.message, 'refactor(') ||
        contains(github.event.head_commit.message, 'test:') ||
        contains(github.event.head_commit.message, 'test(') ||
        contains(github.event.head_commit.message, 'build:') ||
        contains(github.event.head_commit.message, 'build(')))
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Swift 6.0
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test

  release:
    needs: test
    runs-on: ubuntu-latest
    if: |
      always() &&
      github.ref == 'refs/heads/main' && 
      github.event_name == 'push' &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONALTOKEN_SEMANTICRELEASE}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: |
          npm install -g semantic-release
          npm install -g @semantic-release/git
          npm install -g @semantic-release/github
          npm install -g @semantic-release/changelog
          npm install -g @semantic-release/commit-analyzer
          npm install -g @semantic-release/release-notes-generator
          npm install -g conventional-changelog-conventionalcommits

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONALTOKEN_SEMANTICRELEASE}}
        run: semantic-release
